# version: '3.1'
# services:
#   db:
#     image: postgres
#     ports:
#       - 54320:54320
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=password
#       - POSTGRES_DB=productDB


#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080

# docker run --name conteneur_postgres -e POSTGRES_DB=base -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password -p 5432:5432 -d postgres:latest

version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5433:5432"  # Port local : Port PostgreSQL dans le conteneur
    environment:
      POSTGRES_DB: mydatabase  # Nom de la base de données
      POSTGRES_USER: myuser  # Nom d'utilisateur PostgreSQL
      POSTGRES_PASSWORD: mypassword  # Mot de passe PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persiste les données de la base de données

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
